name: List Service Accounts

on:
  workflow_dispatch
jobs:
  list-service-accounts:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.ISHNA_SECRET }}'
       
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
     
    - name: 'Build on gcloud'
      run: 'gcloud builds submit --tag gcr.io/red-plate-341722/webserver'
      
    - name: 'Deploy 4'
      run: 'gcloud run deploy simple-webserver --image=gcr.io/red-plate-341722/webserver:latest --region=us-central1 --allow-unauthenticated --service-account=<new5-483@red-plate-341722.iam.gserviceaccount.com'
